---
# Install gnome packages

- name: unwanted packages are removed
  package:
    name: "{{ gnome_packages_remove }}"
    state: absent
  become: true
  when: gnome_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ gnome_packages_repos }}"
    state: "{{ gnome_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ gnome_packages_prereq }}"
    state: "{{ gnome_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ gnome_packages_install }}"
    state: "{{ gnome_packages_state }}"
  become: true
